# Generated by Django 3.2.3 on 2021-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Accomplishment',
                'verbose_name_plural': 'Accomplishments',
            },
        ),
    ]
